import './globals.css';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { authOption } from './api/auth/[...nextauth]/options';
import SessionSetter from '@/components/utility/SessionSetter';
import { Toaster } from 'sonner';
import { ThemeProvider } from 'next-themes';
import { Poppins } from 'next/font/google';
import Providers from './providers';

const poppins = Poppins({
    subsets: ['latin'],
    display: 'swap',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
    title: 'Nocturn',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getServerSession(authOption);
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${poppins.className}`}>
                <ThemeProvider attribute="class" defaultTheme="system">
                    <Toaster theme="dark" />
                    <Providers>{children}</Providers>
                    <SessionSetter session={session} />
                </ThemeProvider>
            </body>
        </html>
    );
}
