-- CreateEnum
CREATE TYPE "QuizStatus" AS ENUM ('CREATED', 'SCHEDULED', 'PUBLISHED', 'LIVE', 'COMPLETED', 'CANCELLED', 'PAYOUT_PENDING', 'PAYOUT_COMPLETED', 'NULL');

-- AlterTable
ALTER TABLE "quizzes" ADD COLUMN     "status" "QuizStatus" NOT NULL DEFAULT 'CREATED';
